apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    metadata:
      name: ticket-frontend
      labels:
        app: ticket-frontend
    spec:
      containers:
        - name: ticket-frontend
          image: jaga80155/ticket-frontend:{{ .Values.image.tag}}
          ports:
            - containerPort: 80
  replicas: 4
  selector:
    matchLabels:
      app: ticket-frontend
