apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  template:
    metadata:
      name: ticket-redis
      labels:
        app: ticket-redis
    spec:
      containers:
        - name: ticket-redis
          image: redis:alpine
          ports:
            - containerPort: 6379
  replicas: 1
  selector:
    matchLabels:
      app: ticket-redis 